"""Storage contracts for independently editable time entries."""

from datetime import date
from typing import Protocol

from worklogger.domain.worklog.models import WorkLog


class TimeEntryRepository(Protocol):
    def list_for_day(self, user_id: int, day: date) -> tuple[WorkLog, ...]: ...
    def get_entry(self, user_id: int, entry_id: int) -> WorkLog | None: ...
    def save_entry(self, record: WorkLog, *, timer_change: tuple[str | None, str | None] | None = None) -> WorkLog: ...
    def delete_entry(self, user_id: int, entry_id: int, revision: int) -> None: ...
    def change_timer(self, user_id: int, expected: str | None, value: str | None) -> None: ...
