"""Account-scoped work-context storage contract."""

from typing import Protocol
from worklogger.domain.projects.models import Project, WorkItem


class ProjectRepository(Protocol):
    def recent_contexts(self, user_id: int): ...
    def catalog(self, user_id: int) -> tuple[tuple[Project, ...], dict[str, tuple[WorkItem, ...]]]: ...
    def list_projects(self, user_id: int) -> tuple[Project, ...]: ...
    def list_work_items(self, user_id: int, project_id: str) -> tuple[WorkItem, ...]: ...
    def save_project(self, user_id: int, project: Project, *, create: bool) -> Project: ...
    def save_work_item(self, user_id: int, item: WorkItem, *, create: bool) -> WorkItem: ...
